### ISSUE TITLE
Error when running the package

### ISSUE THREAD

**Issue by vr2045** [EccentricWkshp/SS_Tindie#10]
Great project! I get the following error, not sure how to proceed:

{   'Message': 'The request is invalid.',
    'ModelState': {   'storeId': [   "The value '<my_store_name>_Tindie' is not "
                                     'valid for Nullable`1.']}}
Traceback (most recent call last):
  File "ss_tindie.py", line 145, in <module>
    ss_Existing_Shipped = response_shipped['orders']
KeyError: 'orders'

**Comment by eccentricworkshop** [comment]
Looks like it's not getting the right storeId (it seems to think storeId is <my_store_name>_Tindie). In your config file, you need to specify the storeId from ShipStation (a 5 digit number) or rename your ShipStation store name to Tindie and it will be found automatically.

**Comment by vr2045** [comment]
Wow! That worked, thank you so much! No more copying and pasting... I set the store name in SS to Tindie and left it blank in the config file.
